version: '3.8'

services:
  app:
    image: 'leozukich/spring-boot-docker:2'
    build:
      context: .
    container_name: task-project
    depends_on:
      - postgres
      - redis
    environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/task
       - DB_USERNAME=postgres
       - DB_PASSWORD=root123
       - REDIS_HOST=redis
       - REDIS_PORT=6379


    ports:
      - "9002:8080"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_DB=task
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
